package works.eub.voicememo.data.db

import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.*
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class VoiceMemoDaoTest {

    private lateinit var database: VoiceMemoDatabase
    private lateinit var dao: VoiceMemoDao

    @Before
    fun setup() {
        database = Room.inMemoryDatabaseBuilder(
            ApplicationProvider.getApplicationContext(),
            VoiceMemoDatabase::class.java
        ).build()
        dao = database.voiceMemoDao()
    }

    @After
    fun teardown() {
        database.close()
    }

    @Test
    fun insertAndgetAllMemos() = runBlocking {
        val memo = VoiceMemoEntity(title = "Test", content = "Hello world")
        dao.insert(memo)

        val memos = dao.getAllMemos().first()
        assertEquals(1, memos.size)
        assertEquals("Hello world", memos[0].content)
    }

    @Test
    fun getAllMemos_orderByCreatedAtDesc() = runBlocking {
        dao.insert(VoiceMemoEntity(title = "First", content = "1"))
        Thread.sleep(10)
        dao.insert(VoiceMemoEntity(title = "Second", content = "2"))

        val memos = dao.getAllMemos().first()
        assertEquals(2, memos.size)
        assertEquals("2", memos[0].content)
        assertEquals("1", memos[1].content)
    }

    @Test
    fun getById_existing() = runBlocking {
        val id = dao.insert(VoiceMemoEntity(title = "T", content = "C"))
        val memo = dao.getById(id)

        assertNotNull(memo)
        assertEquals("C", memo!!.content)
    }

    @Test
    fun getById_nonExisting() = runBlocking {
        val memo = dao.getById(999)
        assertNull(memo)
    }

    @Test
    fun update_memo() = runBlocking {
        val id = dao.insert(VoiceMemoEntity(title = "Old", content = "Old content"))
        val memo = dao.getById(id)!!.copy(title = "New", content = "New content")
        dao.update(memo)

        val updated = dao.getById(id)
        assertEquals("New content", updated!!.content)
    }

    @Test
    fun delete_memo() = runBlocking {
        val memo = VoiceMemoEntity(title = "T", content = "C")
        val id = dao.insert(memo)
        val inserted = dao.getById(id)!!
        dao.delete(inserted)

        val memos = dao.getAllMemos().first()
        assertTrue(memos.isEmpty())
    }

    @Test
    fun deleteById_memo() = runBlocking {
        val id = dao.insert(VoiceMemoEntity(title = "T", content = "C"))
        dao.deleteById(id)

        val memos = dao.getAllMemos().first()
        assertTrue(memos.isEmpty())
    }

    @Test
    fun getUnsyncedMemos_onlyUnsynced() = runBlocking {
        dao.insert(VoiceMemoEntity(title = "Synced", content = "s", syncedToTasks = true, tasksId = "123"))
        dao.insert(VoiceMemoEntity(title = "Unsynced", content = "u"))

        val unsynced = dao.getUnsyncedMemos()
        assertEquals(1, unsynced.size)
        assertEquals("u", unsynced[0].content)
    }

    @Test
    fun markAsSynced_setsFields() = runBlocking {
        val id = dao.insert(VoiceMemoEntity(title = "T", content = "C"))
        dao.markAsSynced(id, "tasks-42")

        val memo = dao.getById(id)
        assertTrue(memo!!.syncedToTasks)
        assertEquals("tasks-42", memo.tasksId)
    }

    @Test
    fun insert_returnsAutoGeneratedId() = runBlocking {
        val id1 = dao.insert(VoiceMemoEntity(title = "A", content = "1"))
        val id2 = dao.insert(VoiceMemoEntity(title = "B", content = "2"))

        assertNotEquals(id1, id2)
        assertTrue(id1 > 0)
        assertTrue(id2 > 0)
    }

    @Test
    fun deleteById_nonExisting_noException() = runBlocking {
        dao.deleteById(999)
        val memos = dao.getAllMemos().first()
        assertTrue(memos.isEmpty())
    }
}
